### ISSUE TITLE
error in dereplication.

### ISSUE THREAD

**Issue by hanin-alzubaidy** [bowmanlab/seq_data_scripts#1]
I receive an error when I run this function. this is the error message 
(> derepFs <- derepFastq(filtFs, verbose = T)
Error in derepFastq(filtFs, verbose = T) : Not all provided files exist.
> derepRs <- derepFastq(filtRs, verbose = T)
Error in derepFastq(filtRs, verbose = T) : Not all provided files exist.)
I checked the files exists: > table(file.exists(filtFs))

FALSE  TRUE 
    1   193 
> table(file.exists(filtRs))

FALSE  TRUE 
    1   193 
I compared the original directory with the subdirectory (filtered) and I removed the sample that didn't make it to the filtered directory but I still get the same result when I run the file exist command and fore that I get also the same error running derep function.
how can I remove the false data to run the function?
thank you.
https://github.com/bowmanlab/seq_data_scripts/blob/5ed4c750d8d822f5babc00f4f41920bdb6c2f0f5/dada2.r#L58

**Comment by bowmanjeffs** [comment]
Hanin,
It's difficult to say for sure as I have no way to reproduce the error, but it seems like you didn't remove the file name from filtFs?  In that case it's still looking for a file that doesn't exist.  Just add a line of code that drops that file name (and any others that fail QC) from filtFs, filtRs, and sample.names.

Jeff

**Comment by hanin-alzubaidy** [comment]
I haven't removed the file names as you can see in the screenshot. I kept their true names. do you suggest that I re-define filtFs and filtRs?
Excuse me I'm a bit confused.
<img width="1555" alt="Screen Shot" src="https://user-images.githubusercontent.com/29090731/163723594-03727f69-c8a9-4f0c-ac28-07de5f4d3ce9.png">

**Comment by bowmanjeffs** [comment]
Hanin,
Since this isn't a bug with the script I suggest we continue the conversation via email.  I'll reply here then close the thread.  The error message is pretty clear.  You're telling dada2 to execute the function on a file that doesn't exist.  So you need to limit those vectors that I previously mentioned to just those files that actually exist.  If that isn't clear ping me on email.

Jeff
